version: 2

builds:
  - id: "flowcraft"
    main: ./cmd/flowcraft
    binary: flowcraft
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - NOTICE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: Purpose-Dev
    name: flowcraft
  draft: false
  name_template: "Flowcraft {{ .Version }}"
  header: |
    ## Flowcraft {{ .Version }}
    All new features in this version:
  footer: |
    ---
    **Full Changelog:** https://github.com/{{.Env.GITHUB_REPOSITORY}}/compare/{{.PreviousTag}}...{{.Tag}}

changelog:
  sort: asc
  groups:
    - title: 'New Features'
      regexp: '^feat'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix'
      order: 1
    - title: 'Tests'
      regexp: '^test'
      order: 3
    - title: 'Chore & Maintenance'
      regexp: '^chore'
      order: 4
    - title: 'Documentation'
      regexp: '^docs'
      order: 4
    - title: 'Other Commits'
      order: 99
  filters:
    include:
      - '^feat'
      - '^fix'
      - '^test'
      - '^chore'
      - '^docs'
